os: linux
dist: focal
language: node_js
node_js:
- '10'
addons:
  chrome: stable
  ssh_known_hosts:
    - geekwaytothewest.com
    - geekway.com
    - 35.208.234.160
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run gql:codegen
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox ||
  travis_terminate 1;
- ng build --prod
before_install:
- openssl aes-256-cbc -K $encrypted_41efe38679f5_key -iv $encrypted_41efe38679f5_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/geekway/ geekwaytothewest@geekway.com:~/wwwhome/angular.geekwaytothewest.com
  on:
    branch: master
    tags: true
