dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  ssh_known_hosts:
    - geekwaytothewest.com
    - 35.208.234.160

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox || travis_terminate 1;
  - npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_4f6570bf1a14_key -iv $encrypted_4f6570bf1a14_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh -i ./deploy_key geekwaytothewest@geekwaytothewest.com pwd
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/geekway/ geekwaytothewest@geekwaytothewest.com:~/wwwhome/angular.geekwaytothewest.com
  on:
    branch: master
    tags: true